-- ============================================================================
-- MINIAS Database Schema - SQL Server / SQLite Compatible
-- Generated from XSD export
-- ============================================================================

-- 1. OPERATORS (작업자 마스터)
CREATE TABLE OPERATORS (
    OPERATOR VARCHAR(20) PRIMARY KEY
);

-- 2. CODES (프로브 코드 마스터)
CREATE TABLE CODES (
    CODE VARCHAR(11) PRIMARY KEY,
    NAXIS INT,
    PROBE_TYPE VARCHAR(30),
    X_PLUS_DIR SMALLINT,
    X_MINUS_DIR SMALLINT,
    Y_PLUS_DIR SMALLINT,
    Y_MINUS_DIR SMALLINT,
    Z_MINUS_DIR SMALLINT
);

-- 3. SETUP (테스트 설정)
CREATE TABLE SETUP (
    TEST_TYPE VARCHAR(2) PRIMARY KEY,
    NCYCLES INT,
    NAXIS SMALLINT,
    NWORSTDATUMS SMALLINT,
    SIGMA_TEST BIT NOT NULL,
    RANGE_TEST BIT NOT NULL
);

-- 4. LIMITS (테스트 한계값)
CREATE TABLE LIMITS (
    TEST_TYPE VARCHAR(2) PRIMARY KEY,
    MEAN_SIGMA FLOAT,
    MEAN_RANGE FLOAT,
    WORST_RANGE FLOAT,
    MEAN_RANGE_PERFORMANCE FLOAT,
    WORST_RANGE_PERFORMANCE FLOAT,
    MEAN_RANGE_SECOND FLOAT,
    WORST_RANGE_SECOND FLOAT
);

-- 5. TEST RESULTS (테스트 결과 - 메인 테이블)
CREATE TABLE TEST_RESULTS (
    ID_COL INT PRIMARY KEY IDENTITY(1,1),
    DATE DATETIME,
    CODE VARCHAR(20),
    SERIAL_NUMBER VARCHAR(10),
    OPERATOR VARCHAR(20),
    TEST VARCHAR(2),
    RESULT VARCHAR(2),
    MEAN_SIGMA FLOAT,
    MEAN_RANGE FLOAT,
    WORST_SIGMA FLOAT,
    WORST_RANGE FLOAT,
    MEAN_SIGMA_LIMIT FLOAT,
    MEAN_RANGE_LIMIT FLOAT,
    WORST_RANGE_LIMIT FLOAT,
    SECOND_TEST VARCHAR(1),
    FOREIGN KEY (CODE) REFERENCES CODES(CODE),
    FOREIGN KEY (OPERATOR) REFERENCES OPERATORS(OPERATOR)
);

-- 6. TEST AXIS RESULTS (축별 테스트 결과)
CREATE TABLE TEST_AXIS_RESULTS (
    ID_COL INT,
    AXIS SMALLINT,
    DIR VARCHAR(2),
    SIGMA FLOAT,
    RANGE FLOAT,
    RESULT VARCHAR(2),
    NCYCLES INT,
    SECOND_TEST VARCHAR(1),
    PRIMARY KEY (ID_COL, AXIS),
    FOREIGN KEY (ID_COL) REFERENCES TEST_RESULTS(ID_COL)
);

-- 7. TEST SAMPLES (측정 샘플 데이터)
CREATE TABLE TEST_SAMPLES (
    ID_COL INT,
    AXIS SMALLINT,
    CYCLE SMALLINT,
    VALUE FLOAT,
    SECOND_TEST VARCHAR(1),
    WORST_DATUM VARCHAR(1),
    PRIMARY KEY (ID_COL, AXIS, CYCLE),
    FOREIGN KEY (ID_COL) REFERENCES TEST_RESULTS(ID_COL)
);

-- 8. MEASURES (현재 측정값 - 임시)
CREATE TABLE MEASURES (
    AXIS SMALLINT,
    CYCLE INT,
    VALUE FLOAT,
    SECOND_TEST VARCHAR(1),
    WORST_DATUM VARCHAR(1),
    PRIMARY KEY (AXIS, CYCLE)
);

-- 9. MEASURES REGISTERED (등록된 측정값)
CREATE TABLE MEASURES_REGISTERED (
    ID_COL INT PRIMARY KEY,
    DATE DATETIME,
    CODE VARCHAR(20),
    SERIAL_NUMBER VARCHAR(10),
    OPERATOR VARCHAR(20),
    MEAN_SIGMA FLOAT,
    MEAN_RANGE FLOAT,
    WORST_SIGMA FLOAT,
    WORST_RANGE FLOAT,
    SECOND_TEST VARCHAR(1)
);

-- 10. EXCEL SETUP (Excel 출력 설정)
CREATE TABLE EXCEL_SETUP (
    PROBE_TYPE VARCHAR(10),
    CODE VARCHAR(10),
    SERIAL_NUMBER VARCHAR(10),
    OPERATOR VARCHAR(10),
    MEAN_SIGMA VARCHAR(10),
    MEAN_RANGE VARCHAR(10),
    WORST_RANGE VARCHAR(10),
    LIMIT_MEAN_RANGE VARCHAR(10),
    LIMIT_WORST_RANGE VARCHAR(10),
    RESULT VARCHAR(10),
    ASSE1_SIGMA VARCHAR(10),
    ASSE1_RANGE VARCHAR(10),
    ASSE1_START VARCHAR(10),
    DELTA_SECOND SMALLINT
);

-- ============================================================================
-- 주요 쿼리 (EXE에서 추출)
-- ============================================================================

-- 테스트 결과 조회 (코드 정보 포함)
-- SELECT * FROM [TEST RESULTS] 
-- LEFT OUTER JOIN CODES ON [TEST RESULTS].CODE = CODES.CODE
-- WHERE ID_COL = @ID_COL;

-- 축별 결과 조회
-- SELECT * FROM [TEST AXIS RESULTS] WHERE ID_COL = @ID_COL;

